- name: apache base config
  hosts: AR_WebServer
  user: root
  gather_facts: no
  become: True
  vars:
    serveur_admin: webserver
  tasks:
  - name: Set hostname
    hostname:
      name: webserver
  - name: ensure apache is up to date
    yum:
      name: 
      - httpd
      state: latest
  - name: write the apache config file
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
      backup: yes
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: Stop service firewalld if running
    systemd:
      name: firewalld
      state: stopped


  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
