- name: Create the graphical machine for the player from UbuntuTemplate
  vars_files:
    - /home/ansible/ansible_project/roles/connect_vars.yml
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create the VM
    vmware_guest:
      hostname: '{{ vCenter_host }}'
      username: '{{ vCenter_username }}'
      password: '{{ vCenter_password }}'
      validate_certs: False
      name: PlayerMachine
      template: UbuntuTemplate
      datacenter: '{{ vCenter_datacenter }}'
      folder: /
      state: poweredon
      wait_for_ip_address: yes
  - name: Set hostname
    hostname:
      name: player-pc
  - name: Add tags to a virtual machine
    community.vmware.vmware_tag_manager:
      hostname: '{{ vCenter_host }}'
      username: '{{ vCenter_username }}'
      password: '{{ vCenter_password }}'
      tag_names:
        - PlayerMachine
      object_name: PlayerMachine
      object_type: VirtualMachine
      state: add
    delegate_to: localhost

    
