- name: Create the MariaDB database from RockyTemplate
  vars_files:
    - ../connect_vars.yml
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create the VM
    vmware_guest:
      hostname: '{{ vCenter_host }}'
      username: '{{ vCenter_username }}'
      password: '{{ vCenter_password }}'
      validate_certs: False
      name: MariaDB
      template: RockyTemplate
      datacenter: '{{ vCenter_datacenter }}'
      folder: /
      state: poweredon
      wait_for_ip_address: yes
  - name: Set hostname
    hostname:
      name: maria-db
  - name: Add tags to a virtual machine
    community.vmware.vmware_tag_manager:
      hostname: '{{ vCenter_host }}'
      username: '{{ vCenter_username }}'
      password: '{{ vCenter_password }}'
      tag_names:
        - MariaDB
      object_name: MariaDB
      object_type: VirtualMachine
      state: add
    delegate_to: localhost

    
