- name: Create the Terraria Server for the player to use from RockyTemplate
  vars_files:
    - /home/ansible/ansible_project/roles/connect_vars.yml
  hosts: localhost
  user: root
  become: yes
  gather_facts: no
  tasks:
  - name: Create the VM
    vmware_guest:
      hostname: '{{ vCenter_host }}'
      username: '{{ vCenter_username }}'
      password: '{{ vCenter_password }}'
      validate_certs: False
      name: TerrariaServer
      template: RockyTemplate
      datacenter: '{{ vCenter_datacenter }}'
      folder: /
      state: poweredon
      wait_for_ip_address: no
  - name: Add tags to a virtual machine
    community.vmware.vmware_tag_manager:
      hostname: '{{ vCenter_host }}'
      username: '{{ vCenter_username }}'
      password: '{{ vCenter_password }}'
      tag_names:
        - Ansible_managed:AR_TerrariaServer
      object_name: TerrariaServer
      object_type: VirtualMachine
      state: add
      validate_certs: no
    
