- name: Install the server and run it
  hosts: AR_TerrariaServer
  user: root
  gather_facts: no
  become: True
  vars:
    server_dl_link: "https://terraria.org/api/download/pc-dedicated-server/terraria-server-1432.zip"
  tasks:
  - name: Install dependencies
    yum:
      name: 
      - wget
      - temux
      - unzip
      state: latest
  - name: Get server zip
    get_url:
      url: '{{ server_dl_link }}'
      dest: /opt/tServer.zip
      mode: '0744'
  - name: Unzip the server
    unarchive:
      src: /opt/tServer.zip
      dest: /opt/tServer_unzipped
  - name: Make Server executable
    file:
      path: /opt/tServer_unzipped/1432/Linux/TerrariaServer.bin.x86_64
      owner: ansible
      group: ansible
      mode: '0744'
  - name: Add server config
    template:
      src: serverconfig.txt
      dest: /opt/tServer_unzipped/1432/Linux/serverconfig.txt
      owner: ansible
      group: ansible
      mode: '0744'
  - name: Run the server
    shell: /opt/tServer_unzipped/1432/Linux/TerrariaServer.bin.x86_64
  - name: Stop service firewalld if running
    systemd:
      name: firewalld
      state: stopped
