- name: Install the server and run it
  hosts: AR_TerrariaServer
  user: root
  gather_facts: no
  become: True
  tasks:
  - name: Set hostname
    hostname:
      name: terrariaserver
  - name: Install dependencies
    yum:
      name: 
      - wget
      - tmux
      - unzip
      state: latest
  - name: Unzip the server
    unarchive:
      src: tServer.zip
      remote_dest: /opt/tServer_unzipped
  - name: Make Server executable
    file:
      path: /opt/tServer_unzipped/1432/Linux/TerrariaServer.bin.x86_64
      owner: ansible
      group: ansible
      mode: '0744'
  - name: Add server config
    template:
      src: serverconfig.txt
      dest: /opt/tServer_unzipped/1432/Linux/serverconfig.txt
      owner: ansible
      group: ansible
      mode: '0744'
  - name: Run the server
    shell: /opt/tServer_unzipped/1432/Linux/TerrariaServer.bin.x86_64
  - name: Stop service firewalld if running
    systemd:
      name: firewalld
      state: stopped
